import customtkinter as ctk
import os
import subprocess
import threading
import sys
import platform
import shutil
from pathlib import Path
from typing import List, Optional

# --- КОНФИГУРАЦИЯ ---
class Config:
    APP_NAME = "NewEngine Studio"
    VERSION = "0.3.0" # Smart Build Update
    THEME = "Dark"
    ACCENT_COLOR = "blue"
    
    ROOT_DIR = Path(os.getcwd())
    BIN_DIR = ROOT_DIR / "bin"
    OBJ_DIR = BIN_DIR / "obj" # Папка для промежуточных файлов
    INCLUDE_DIR = ROOT_DIR / "include"
    ASSETS_DIR = ROOT_DIR / "assets"
    
    COMPILER = "gcc"
    OUTPUT_NAME = "game"
    if platform.system() == "Windows":
        OUTPUT_NAME += ".exe"

# --- ЛОГИКА КОНВЕРТАЦИИ ---
class AssetConverter:
    @staticmethod
    def convert_obj_to_h(obj_path: Path) -> str:
        name = obj_path.stem.lower().replace(" ", "_")
        vertices, faces = [], []
        
        try:
            with open(obj_path, 'r') as f:
                for line in f:
                    if line.startswith('v '):
                        p = line.split()
                        vertices.append(f"    {{{p[1]}, {p[2]}, {p[3]}}}")
                    elif line.startswith('f '):
                        p = line.split()
                        idx = [str(int(part.split('/')[0]) - 1) for part in p[1:]]
                        if len(idx) == 3: faces.append(f"    {{{idx[0]}, {idx[1]}, {idx[2]}}}")
                        elif len(idx) == 4:
                            faces.append(f"    {{{idx[0]}, {idx[1]}, {idx[2]}}}")
                            faces.append(f"    {{{idx[0]}, {idx[2]}, {idx[3]}}}")

            content = f"#pragma once\n\n// Generated by NewEngine Studio\n\n"
            content += f"static const NE_Vertex {name}_v[] = {{\n" + ",\n".join(vertices) + "\n};\n\n"
            content += f"static const NE_Color {name}_c[] = {{\n" + ",\n".join(["    {1.0, 1.0, 1.0, 1.0}"] * len(vertices)) + "\n};\n\n"
            content += f"static const NE_Face {name}_f[] = {{\n" + ",\n".join(faces) + "\n};\n\n"
            content += f"static const NE_Model {name}_model = {{\n    {name}_v,\n    {name}_c,\n    {name}_f,\n    {len(faces)}\n}};\n"
            return content
        except Exception as e: return f"ERROR: {str(e)}"

# --- ЛОГИКА ПРОЕКТА ---
class ProjectManager:
    @staticmethod
    def scan_sources() -> List[Path]:
        sources = []
        dirs_to_scan = [Config.ROOT_DIR / "engine", Config.ROOT_DIR / "game"]
        for directory in dirs_to_scan:
            if directory.exists():
                for file in directory.rglob("*.c"):
                    sources.append(file)
        return sources

    @staticmethod
    def get_common_flags() -> List[str]:
        return [f"-I{Config.INCLUDE_DIR}", f"-I{Config.ASSETS_DIR}", "-g", "-Wall"]

    @staticmethod
    def get_linker_flags() -> List[str]:
        system = platform.system()
        if system == "Windows":
            return ["-lopengl32", "-lglu32", "-lgdi32", "-lwinmm"]
        elif system == "Linux":
            return ["-lGL", "-lGLU", "-lm", "-lX11", "-lXrandr"]
        elif system == "Darwin":
            return ["-framework", "OpenGL", "-framework", "Cocoa", "-framework", "IOKit"]
        return []

# --- СИСТЕМА СБОРКИ (ОБНОВЛЕННАЯ) ---
class BuildSystem:
    def __init__(self, app_instance):
        self.app_instance = app_instance
        self.console_log = app_instance.log_to_console
        self.game_process: Optional[subprocess.Popen] = None

    def build(self, run_after=False):
        threading.Thread(target=self._build_task, args=(run_after,), daemon=True).start()

    def _build_task(self, run_after):
        self.app_instance.set_ui_busy(True)
        self.app_instance.clear_console()
        self.console_log("--- ЗАПУСК УМНОЙ СБОРКИ ---\n", "info")
        
        # Подготовка папок
        Config.BIN_DIR.mkdir(exist_ok=True)
        Config.OBJ_DIR.mkdir(exist_ok=True)
        
        sources = ProjectManager.scan_sources()
        object_files = []
        has_error = False

        # ШАГ 1: Компиляция каждого файла в .o
        for src_path in sources:
            rel_path = src_path.relative_to(Config.ROOT_DIR)
            
            # Создаем уникальное имя для .o файла (заменяем слэши на подчеркивания)
            obj_name = str(rel_path).replace(os.sep, "_").replace(".c", ".o")
            obj_path = Config.OBJ_DIR / obj_name
            object_files.append(str(obj_path))
            
            cmd = [Config.COMPILER, "-c", str(src_path), "-o", str(obj_path)] + ProjectManager.get_common_flags()
            
            # === ГЛАВНЫЙ ТРЮК ===
            # Если это engine/main.c, переименовываем main в __dummy_main
            if "engine" in src_path.parts and src_path.name == "main.c":
                self.console_log(f"[TRICK] Глушим main() в {rel_path}...\n", "warning")
                cmd.append("-Dmain=__engine_dummy_main")
            # ====================

            self.console_log(f"Compiling: {rel_path}...\n", "dim")
            
            try:
                # Запускаем компиляцию одного файла
                proc = subprocess.run(cmd, capture_output=True, text=True, cwd=Config.ROOT_DIR)
                
                if proc.stdout: self.console_log(proc.stdout)
                if proc.stderr: 
                    tag = "error" if "error:" in proc.stderr.lower() else "warning"
                    self.console_log(proc.stderr, tag)
                
                if proc.returncode != 0:
                    has_error = True
                    break # Останавливаемся при первой ошибке
                    
            except Exception as e:
                self.console_log(f"Ошибка вызова GCC: {e}\n", "error")
                has_error = True
                break

        # ШАГ 2: Линковка (Сборка .o файлов в .exe)
        if not has_error:
            self.console_log("\nЛинковка исполняемого файла...\n", "info")
            output_path = Config.BIN_DIR / Config.OUTPUT_NAME
            
            link_cmd = [Config.COMPILER] + object_files + ["-o", str(output_path)] + ProjectManager.get_linker_flags()
            
            try:
                proc = subprocess.run(link_cmd, capture_output=True, text=True, cwd=Config.ROOT_DIR)
                
                if proc.stdout: self.console_log(proc.stdout)
                if proc.stderr: self.console_log(proc.stderr, "warning") # Линковщик часто пишет инфо в stderr
                
                if proc.returncode == 0:
                    self.console_log(f"УСПЕШНО: {output_path}\n", "success")
                    if run_after: self.run_game()
                else:
                    self.console_log(f"Ошибка линковки (код {proc.returncode})\n", "error")
                    
            except Exception as e:
                self.console_log(f"Ошибка линковщика: {e}\n", "error")
        else:
            self.console_log("Сборка остановлена из-за ошибок.\n", "error")

        self.app_instance.set_ui_busy(False)

    def run_game(self):
        exe_path = Config.BIN_DIR / Config.OUTPUT_NAME
        if not exe_path.exists():
            self.console_log("ОШИБКА: Файл игры не найден.\n", "error")
            return
        
        # Убиваем старый процесс, если он жив
        if self.game_process and self.game_process.poll() is None:
            try:
                self.game_process.terminate()
                self.console_log("Старый процесс игры остановлен.\n", "dim")
            except: pass

        self.console_log("--- ЗАПУСК ИГРЫ ---\n", "info")
        try:
            self.game_process = subprocess.Popen([str(exe_path)], cwd=Config.ROOT_DIR)
        except Exception as e:
            self.console_log(f"ОШИБКА ЗАПУСКА: {e}\n", "error")

# --- UI КОМПОНЕНТЫ ---
class LogPanel(ctk.CTkTextbox):
    def __init__(self, master, **kwargs):
        super().__init__(master, **kwargs)
        self.configure(state="disabled", font=("Consolas", 12))
        self.tag_config("error", foreground="#ff5555")
        self.tag_config("warning", foreground="#ffb86c")
        self.tag_config("success", foreground="#50fa7b")
        self.tag_config("info", foreground="#8be9fd")
        self.tag_config("dim", foreground="#6272a4")

    def write(self, text, tag=None):
        self.configure(state="normal")
        if tag: self.insert("end", text, tag)
        else: self.insert("end", text)
        self.see("end")
        self.configure(state="disabled")
        
    def clear(self):
        self.configure(state="normal")
        self.delete("1.0", "end")
        self.configure(state="disabled")

# --- ГЛАВНОЕ ОКНО ---
class StudioApp(ctk.CTk):
    def __init__(self):
        super().__init__()
        self.title(f"{Config.APP_NAME} v{Config.VERSION}")
        self.geometry("1100x700")
        ctk.set_appearance_mode(Config.THEME)
        
        self.build_system = BuildSystem(self)
        
        self.grid_columnconfigure(1, weight=1)
        self.grid_rowconfigure(0, weight=1)

        # 1. ЛЕВОЕ МЕНЮ
        self.sidebar = ctk.CTkFrame(self, width=200, corner_radius=0)
        self.sidebar.grid(row=0, column=0, sticky="nsew")
        self.sidebar.grid_rowconfigure(5, weight=1)

        ctk.CTkLabel(self.sidebar, text="NEW ENGINE\nSTUDIO", font=ctk.CTkFont(size=20, weight="bold")).pack(pady=20)
        
        self.btn_build = ctk.CTkButton(self.sidebar, text="🔨 Компилировать", command=lambda: self.build_system.build(False))
        self.btn_build.pack(padx=20, pady=10)
        
        self.btn_run = ctk.CTkButton(self.sidebar, text="▶ Запустить", command=self.build_system.run_game, fg_color="green", hover_color="darkgreen")
        self.btn_run.pack(padx=20, pady=10)
        
        self.btn_br = ctk.CTkButton(self.sidebar, text="🚀 Build & Run", command=lambda: self.build_system.build(True))
        self.btn_br.pack(padx=20, pady=10)

        # 2. ПРАВАЯ ЧАСТЬ
        self.tab_view = ctk.CTkTabview(self)
        self.tab_view.grid(row=0, column=1, padx=10, pady=10, sticky="nsew")
        
        # Вкладка 1
        self.tab_code = self.tab_view.add("Код & Логи")
        self.tab_code.grid_columnconfigure(0, weight=1)
        self.tab_code.grid_rowconfigure(1, weight=1)
        
        self.file_frame = ctk.CTkScrollableFrame(self.tab_code, height=200)
        ctk.CTkLabel(self.file_frame, text="Исходные файлы проекта", font=("Arial", 12, "bold")).pack(fill="x", pady=5)
        self.file_frame.grid(row=0, column=0, sticky="ew", pady=(0, 10))
        self.refresh_files()
        
        self.console = LogPanel(self.tab_code)
        self.console.grid(row=1, column=0, sticky="nsew")

        # Вкладка 2
        self.tab_assets = self.tab_view.add("Ассеты (3D)")
        self.setup_assets_tab()

    def setup_assets_tab(self):
        self.tab_assets.grid_columnconfigure(0, weight=1)
        info_lbl = ctk.CTkLabel(self.tab_assets, text="Конвертер 3D моделей (.obj -> .h)", font=("Arial", 16, "bold"))
        info_lbl.pack(pady=20)
        
        self.btn_select_obj = ctk.CTkButton(self.tab_assets, text="Выбрать .obj файл", command=self.select_obj_file)
        self.btn_select_obj.pack(pady=10)
        self.lbl_selected_file = ctk.CTkLabel(self.tab_assets, text="Файл не выбран", text_color="gray")
        self.lbl_selected_file.pack(pady=5)
        self.btn_convert = ctk.CTkButton(self.tab_assets, text="Сконвертировать в код", command=self.convert_obj, state="disabled")
        self.btn_convert.pack(pady=20)
        self.log_assets = ctk.CTkTextbox(self.tab_assets, height=150)
        self.log_assets.pack(fill="x", padx=20, pady=20)
        self.log_assets.insert("1.0", "Здесь будет результат конвертации...")
        self.selected_obj_path: Optional[Path] = None

    def select_obj_file(self):
        file_path = ctk.filedialog.askopenfilename(filetypes=[("OBJ Files", "*.obj")])
        if file_path:
            self.selected_obj_path = Path(file_path)
            self.lbl_selected_file.configure(text=f"Выбран: {self.selected_obj_path.name}", text_color="white")
            self.btn_convert.configure(state="normal")

    def convert_obj(self):
        if not self.selected_obj_path: return
        Config.ASSETS_DIR.mkdir(exist_ok=True)
        code = AssetConverter.convert_obj_to_h(self.selected_obj_path)
        if code.startswith("ERROR"):
            self.log_assets.delete("1.0", "end"); self.log_assets.insert("1.0", code)
            return
        out_name = self.selected_obj_path.stem.lower().replace(" ", "_") + ".h"
        out_path = Config.ASSETS_DIR / out_name
        with open(out_path, "w") as f: f.write(code)
        self.log_assets.delete("1.0", "end")
        self.log_assets.insert("1.0", f"УСПЕХ! Сохранен: {out_path}\nДобавь в game/main.c:\n#include <{out_name}>\nИспользуй: {self.selected_obj_path.stem.lower()}_model")
        self.console.write(f"[ASSET] Сконвертирована модель: {out_name}\n", "success")

    def refresh_files(self):
        for widget in self.file_frame.winfo_children(): 
            if isinstance(widget, ctk.CTkLabel) and widget.cget("text") != "Исходные файлы проекта": widget.destroy()
        for src in ProjectManager.scan_sources():
            ctk.CTkLabel(self.file_frame, text=f"📄 {src.relative_to(Config.ROOT_DIR)}", anchor="w").pack(fill="x", padx=5)

    def log_to_console(self, text, tag=None): self.after(0, lambda: self.console.write(text, tag))
    def clear_console(self): self.after(0, lambda: self.console.clear())
    def set_ui_busy(self, busy: bool):
        st = "disabled" if busy else "normal"
        self.btn_build.configure(state=st); self.btn_run.configure(state=st); self.btn_br.configure(state=st)

if __name__ == "__main__":
    app = StudioApp()
    app.mainloop()